name: Update r-sdk SDK

on:
  # Çàïóñêàòèñÿ ðàç íà òèæäåíü (ó íåä³ëþ î 00:00 çà UTC)
  schedule:
    - cron: '0 0 * * 0'
  # Äîäàòêîâî, ùîá ìàòè ìîæëèâ³ñòü çàïóñòèòè âðó÷íó
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_r_sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download r.tgz
        run: |
          curl -L -o r.tgz https://app.api2cart.com/sdk/openapi/r.tgz


      - name: Commit changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update r SDK [skip ci]"
          git push
